FROM python:3.7
RUN pip install --upgrade pip
RUN pip install --no-cache-dir mysql-connector-python
RUN pip install --no-cache-dir django
RUN pip install --no-cache-dir djangorestframework
RUN pip install --no-cache-dir django-filter 