version: '3'
services:
  app:
    container_name: 'python3'
    build: ./docker/python
    volumes:
      - ./app:/app
    tty: true
  db:
    image: mysql:5.7
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./data:/var/lib/mysql
    - ./docker/mysql/conf.d:/etc/mysql/conf.d
    - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8080:80